name: Check if releaseable

on:
  workflow_call:
    outputs:
      result:
          description: The result of the check (1 -> release, 0 -> no release)
          value: ${{ jobs.check.outputs.result }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check.outputs.result }}
    steps:
    - uses: actions/checkout@v4
    - name: Check for release
      id: check
      if: contains(github.event.head_commit.message, '[release]')
      run: |
        CHANGELOG=$(grep "Nothing changed yet." CHANGES.rst >/dev/null; echo $?)
        echo $CHANGELOG
        echo "result=${CHANGELOG}" >> $GITHUB_OUTPUT
