name: Cleanup

on:
  workflow_call:
    inputs:
      expire_in:
        default: "2days"
        required: false
        type: string

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    if: ${{ false }}  # disable for now
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: ${{ inputs.expire_in }}
