name: Deploy

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
    secrets:
      CLONE_KEY:
        required: true
      SSH_CONFIG:
        required: true
      SSH_PRIVATE_KEY:
        required: true

jobs:
  deploy:
    runs-on: self-hosted
    env:
      TARGET: ''
    steps:
    - uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.CLONE_KEY }}
    - name: Checkout kravagonline_deployment
      run: git clone git@github.com:risclog-solution/kravagonline_deployment.git $GITHUB_WORKSPACE
    - name: Update branch ${{ inputs.target }}
      run: |
        cd $GITHUB_WORKSPACE
        git config --local user.email "info@risclog.de"
        git config --local user.name "risclog"
        git checkout ${{ inputs.target }}
        source="master" && [[ ${{ inputs.target }} == "production" ]]  && source="staging"
        git merge origin/$source
        git push
    - name: Setup SSH access
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan fcio.net >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_CONFIG }}" > ~/.ssh/config
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/identity
    - name: Deploy to ${{ inputs.target }}
      run: |
        ./batou deploy ${{ inputs.target }}
