name: Deploy

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      repository:
        required: true
        type: string
    secrets:
      CLONE_KEY:
        required: true
      SSH_CONFIG:
        required: true
      SSH_PRIVATE_KEY:
        required: true

jobs:
  deploy:
    runs-on: self-hosted
    env:
      TARGET: ''
    steps:
    - uses: AutoModality/action-clean@v1
    - name: Setup SSH access
      run: |
        mkdir -p ~/.ssh
        rm ~/.ssh/known_hosts
        ssh-keyscan fcio.net >> ~/.ssh/known_hosts
        echo "github.com,140.82.118.3 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_CONFIG }}" > ~/.ssh/config
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/identity
        echo "${{ secrets.CLONE_KEY }}" > ~/.ssh/id_rsa
    - name: Checkout github.com:risclog-solution/${{ inputs.repository }}.git
      run: git clone git@github.com:risclog-solution/${{ inputs.repository }}.git $GITHUB_WORKSPACE
    - name: Update branch ${{ inputs.target }}
      run: |
        cd $GITHUB_WORKSPACE
        git config --local user.email "info@risclog.de"
        git config --local user.name "risclog"
        git checkout ${{ inputs.target }}
        source="master" && [[ ${{ inputs.target }} == "production" ]]  && source="staging"
        git merge origin/$source
        git push
    - name: Deploy to ${{ inputs.target }}
      run: |
        ./batou deploy ${{ inputs.target }}
