name: Deploy

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      repository:
        required: true
        type: string
    secrets:
      CLONE_KEY:
        required: true
      SSH_CONFIG:
        required: true
      SSH_PRIVATE_KEY:
        required: true

jobs:
  deploy:
    runs-on: self-hosted
    env:
      TARGET: ''
    steps:
    - name: Setup SSH access
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan fcio.net >> ~/.ssh/known_hosts
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_CONFIG }}" > ~/.ssh/config
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/identity
        echo "${{ secrets.CLONE_KEY }}" > ~/.ssh/id_rsa
    - name: Run tmate
      uses: mxschmitt/action-tmate@master
      with:
        sudo: false
        install-dependencies: false
    - name: Checkout github.com:risclog-solution/${{ inputs.repository }}.git
      run: git clone git@github.com:risclog-solution/${{ inputs.repository }}.git $GITHUB_WORKSPACE
    - name: Update branch ${{ inputs.target }}
      run: |
        cd $GITHUB_WORKSPACE
        git config --local user.email "info@risclog.de"
        git config --local user.name "risclog"
        git checkout ${{ inputs.target }}
        source="master" && [[ ${{ inputs.target }} == "production" ]]  && source="staging"
        git merge origin/$source
        git push
    - name: Deploy to ${{ inputs.target }}
      run: |
        ./batou deploy ${{ inputs.target }}
