name: Deploy

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      repository:
        required: true
        type: string
    secrets:
      CLONE_KEY:
        required: true
      SSH_CONFIG:
        required: true
      SSH_PRIVATE_KEY:
        required: true

jobs:
  deploy:
    runs-on: self-hosted
    env:
      TARGET: ''
    steps:
    - uses: AutoModality/action-clean@v1
    - name: Setup SSH access
      run: |
        mkdir -p /root/.ssh
        # rm ~/.ssh/known_hosts
        ssh-keyscan fcio.net >> /root/.ssh/known_hosts
        ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts
        echo "${{ secrets.SSH_CONFIG }}" > /root/.ssh/config
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > /root/.ssh/identity
        echo "${{ secrets.CLONE_KEY }}" > /root/.ssh/id_rsa
    - name: Checkout github.com:risclog-solution/${{ inputs.repository }}.git
      run: |
          git clone --verbose git@github.com:risclog-solution/${{ inputs.repository }}.git $GITHUB_WORKSPACE
    - name: Update branch ${{ inputs.target }}
      run: |
        cd $GITHUB_WORKSPACE
        git config --local user.email "info@risclog.de"
        git config --local user.name "risclog"
        git checkout ${{ inputs.target }}
        source="master" && [[ ${{ inputs.target }} == "production" ]]  && source="staging"
        git merge origin/$source
        git push
    - name: Deploy to ${{ inputs.target }}
      run: |
        ./batou deploy ${{ inputs.target }}
