name: Pre-commit

on:
  workflow_call:
    inputs:
      python_version:
        default: "3.10"
        required: false
        type: string

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
    - uses: pre-commit/action@v3.0.0
