name: Release

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
    outputs:
      version:
          description: The version of the released package
          value: ${{ jobs.release.outputs.version }}
    secrets:
      PYPIRC:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.pin.outputs.version }}
    steps:
    - uses: actions/checkout@v3
    - name: Prepare git client
      run: |
        git config --local user.email "info@risclog.de"
        git config --local user.name "risclog"
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install zest.releaser
      run: |
        python -m pip install --upgrade pip
        pip install zest.releaser[recommended]
        echo "$pypirc" > ~/.pypirc
        fullrelease --no-input
      env:
        pypirc: ${{ secrets.PYPIRC }}
    - name: Pin new version
      id: pin
      run: |
        VERSION=$(git tag | tail -1)
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        START=$(grep -n "^$VERSION (" CHANGES.rst | cut --delimiter=":" --fields=1)
        START=$(expr $START + 2)
        END=$(tail -n +$START CHANGES.rst  | grep -n "^============" -m 1 | cut --delimiter=":" --fields=1)
        END=$(expr $START + $END)
        END=$(expr $END - 4)
        CHANGELOG=$(head -n $END CHANGES.rst | tail -n $(($END-$START+1)))
        CHANGELOG="${CHANGELOG//$'\r'/}"
        CHANGELOG="${CHANGELOG//$'\n'/:::}"
        CHANGELOG="${CHANGELOG//:::/\n}"
        echo "changelog=${CHANGELOG}" >> $GITHUB_OUTPUT
        curl -H 'Content-Type: application/json' -d '{"msg": "new release: `${{ inputs.package_name }}` `'${VERSION}'`:\n\nCHANGELOG: https://github.com/risclog-solution/${{ inputs.package_name }}/blob/'${VERSION}'/CHANGES.rst\n'${CHANGELOG}'"}' https://bots.keybase.io/webhookbot/KheIE65MgRKhVG6yp3fo_IdEof8
