name: Release

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      branch_protection:
        required: false
        type: string
        default: "disabled"
    outputs:
      version:
          description: The version of the released package
          value: ${{ jobs.release.outputs.version }}
    secrets:
      PYPIRC:
        required: true
      BUILD_SVC_PAT:
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.pin.outputs.version }}
    steps:
    - name: Checkout repo with authenticated git commands
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.BUILD_SVC_PAT }}
    - name: Prepare git client
      run: |
        git config --local user.email "info@risclog.de"
        git config --local user.name "risclog"
    - name: Set up Python 3
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install zest.releaser
      run: |
        python -m pip install --upgrade pip
        pip install twine==6.1.0
        pip install "zest.releaser[recommended]==9.1.1"
        pip install risclog.zestreleaser.notify
        echo "$pypirc" > ~/.pypirc
        fullrelease --no-input
      env:
        pypirc: ${{ secrets.PYPIRC }}
    - name: Pin new version
      id: pin
      run: |
        VERSION=$(git tag | tail -1)
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
