name: SonarQube

on:
  workflow_call:
    secrets:
      SONARQUBETOKEN:
        required: true

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: SonarQube Scan
      uses: risclog-solution/sonarqube-action@master
      with:
        host: https://sonarqube.risclog.fcio.net
        login: ${{ secrets.SONARQUBETOKEN }}
