name: SonarQube

on:
  workflow_call:
    secrets:
      SONARQUBETOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.1.1
      with:
        host: https://sonarqube.risclog.fcio.net
        login: ${{ secrets.SONARQUBETOKEN }}
