name: SonarQube

on:
  workflow_call:
    inputs:
      project_type:
        default: "python"
        required: false
        type: string

    secrets:
      SONARQUBETOKEN:
        required: true

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
